version: '3.8'

services:
  imdb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      imdb-db:
        condition: service_healthy
    networks:
      - imdb-network
    restart: unless-stopped

  imdb-db:
    container_name: imdb-db
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - imdb-db:/var/lib/postgresql/data
      - ./postgres/data:/postgres/data
#      - ./postgres/data/limited:/postgres/data/limited
      - ./postgres/init:/docker-entrypoint-initdb.d
    command: postgres -c 'max_wal_size=20GB' -c 'checkpoint_timeout=300s'
    ports:
      - "5444:5432"
    networks:
      - imdb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d imdb"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  imdb-network:
    driver: bridge

volumes:
  imdb-db:
